# Generated by Django 3.1.9 on 2022-02-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grams', models.FloatField()),
                ('cost', models.FloatField()),
                ('in_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('paid', models.BooleanField(blank=True, default=False)),
                ('ready', models.BooleanField(blank=True, default=False)),
                ('delivered', models.BooleanField(blank=True, default=False)),
                ('dishes', models.ManyToManyField(to='restaurant.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='ingridients',
            field=models.ManyToManyField(to='restaurant.Ingridient'),
        ),
    ]
